### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by rohitbakoliya** [rohitbakoliya/bit-manipulation#1]

**Comment by jsmiith** [comment]
What?

**Comment by rohitbakoliya** [comment]
> What do you want to be done? The issue wasn't very informative.

you have to add only your favourite bit-manipulation problem.
like - given number is of 2's power or not? 
count number of set bits

**Comment by rohitbakoliya** [comment]
> What do you want to be done? The issue wasn't very informative.
